let constants = {
    min: document.getElementById('minutes'),
    sec: document.getElementById('seconds'),
    mapElt: document.getElementById('map'),
    detailsStation: document.getElementById('stationDetails'),
    titleElt: document.getElementById('titleElt'),
    divElt: document.getElementById('divElt'),
    div2Elt: document.getElementById('div2Elt'),
    div3Elt: document.getElementById('div3Elt'),
    div4Elt: document.getElementById('div4Elt'),
    div5Elt: document.getElementById('div5Elt'),
    pElt: document.getElementById('pElt'),
    p2Elt: document.getElementById('p2Elt'),
    btnReserverElt: document.getElementById('btnReserverVelo'),
    noReservation: document.getElementById('noReservation'),
    pTimerElmt: document.getElementById('pTimer'),
    btnTimerElmt: document.getElementById('cancelBtn'),
    endTimerMessage: document.getElementById('endTimerMessage'),
    figureElt: document.getElementById('figureSign'),
    signDivElt: document.getElementById('signDivElt'),
    loading: document.getElementById('loading'),
    sectionCanvas: document.getElementById('sectionCanvas'),
    bookingContainer: document.getElementById('bookingContainer'),
    imgElt: document.getElementById('imgSignature'),
    titreCanvas: document.getElementById('titre-canvas'),
    canvas: document.getElementById('canvas'),
    canvasVerification: document.getElementById('canvasVerification'),
    submitElt: document.getElementById('sign'),
    resetElt: document.getElementById('reset'),
    nextBtn: document.getElementById('next'),
    prevBtn: document.getElementById('prev'),
    pauseBtn: document.getElementById('pause'),
    contractModal: document.getElementById('contractModal'),
    modalLink: document.getElementById('modalLink'),
    legalNoticeLink: document.getElementById('legalNoticeLink'),
    legalNotice: document.getElementById('legalNotice'),
    closeLegalNotice: document.getElementById('closeLegalNotice'),
    streetViewMap: document.getElementById('streetViewMap'),
};

export default constants;